# Generated by Django 5.2.1 on 2025-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_date_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('planned', 'Planned')], default='draft', max_length=20),
        ),
    ]
