# Generated by Django 5.2.1 on 2025-08-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sobre mí', max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='about/')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_technologies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technology.technology')),
            ],
        ),
    ]
