# Generated by Django 5.2.1 on 2025-08-27 14:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv_file'),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
