# Generated by Django 5.2.1 on 2025-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_cv_file_alter_about_photo'),
        ('technology', '0002_technology_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='main_technologies',
        ),
        migrations.AddField(
            model_name='about',
            name='main_technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='about_technologies', to='technology.technology'),
        ),
    ]
