# Generated by Django 5.2.1 on 2025-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
